=== williamchankc35/IP/XML/CustomerXML.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT CustomerTable (CustomerRow+)>

<!ELEMENT CustomerRow(CusID, CusType, CusName,Username, Password, Email,CreditLimit,Status)>
<!ELEMENT CusID (#PCDATA)>
<!ELEMENT CusType (#PCDATA)>
<!ELEMENT CusName (#PCDATA)>
<!ELEMENT Username (#PCDATA)>
<!ELEMENT Password (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT CreditLimit (#PCDATA)>
<!ELEMENT Status (#PCDATA)>

=== williamchankc35/IP/XML/CustomerXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="CustomerXML.xsl"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE CustomerTable SYSTEM 'CustomerXML.dtd'>


<CustomerTable>
    <CustomerRow>
        <CusID>CS0001</CusID>
        <CusType>Corporate</CusType>
        <CusName>Leong Tzee Yang</CusName>
        <Username>LTY</Username>
        <Password>LTY</Password>
        <Email>LTY@hotmail.com</Email>
        <CreditLimit>5000.00</CreditLimit>
        <Status>Good</Status>
                    
    </CustomerRow>
      <CustomerRow>
        <CusID>CS0002</CusID>
        <CusType>Corporate</CusType>
        <CusName>Leong Tzee Yang</CusName>
        <Username>LTY</Username>
        <Password>LTY</Password>
        <Email>LTY@hotmail.com</Email>
        <CreditLimit>5000.00</CreditLimit>
        <Status>Good</Status>
                    
    </CustomerRow>
</CustomerTable>
